### PR TITLE
Implement BillEase for PH: create admin settings

### PR DESCRIPTION
**Pull request by andykim**
## Description

Implement BillEase for PH: create admin settings

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Cosmetic change (text changing or color changing)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code (if necessary), particularly in hard-to-understand areas
- [ ] My changes generate no new vulnerabilities
- [ ] I have added tests that prove my fix is effective or that my feature works

## Screenshot
Screenshot from 2022-02-07 20-45-50

### CODE REVIEW

**Review by candrasaputra — APPROVED** [review]

**Review by kevinalfianto — APPROVED** [review]

**Review by IreneGohtami — COMMENTED** [review]
Do we display both ID & PH payment settings in the same page? If yes, can we add a check to display PH payment if the store's currency is set to PHP? @andykim

**Comment by andykim** [comment]
@IreneGohtami 

> Do we display both ID & PH payment settings in the same page? If yes, can we add a check to display PH payment if the store's currency is set to PHP? @andykim

Yes, the ID & PH payment settings are on the same page. So I'm thinking about splitting them by 2 setting block like this 
Screenshot from 2022-02-08 10-25-37

so they have the setting for PH payment & ID payment.

**Comment by IreneGohtami** [comment]
> @IreneGohtami
> 
> > Do we display both ID & PH payment settings in the same page? If yes, can we add a check to display PH payment if the store's currency is set to PHP? @andykim
> 
> Yes, the ID & PH payment settings are on the same page. So I'm thinking about splitting them by 2 setting block like this Screenshot from 2022-02-08 10-25-37
> 
> so they have the setting for PH payment & ID payment.

I still prefer if we can show & hide, because our merchants would most likely on need either ID/PH & not both. This apply to the checkout page as well. @andykim

**Comment by andykim** [comment]
> 
> I still prefer if we can show & hide, because our merchants would most likely on need either ID/PH & not both. This apply to the checkout page as well. @andykim

Ok. Let me try on this. Actually, Magento does not support it, so I need to customize our plugin. 

But it is a good idea @IreneGohtami . can you create a ticket on Jira for it.?

**Comment by IreneGohtami** [comment]
> > I still prefer if we can show & hide, because our merchants would most likely on need either ID/PH & not both. This apply to the checkout page as well. @andykim
> 
> Ok. Let me try on this. Actually, Magento does not support it, so I need to customize our plugin.
> 
> But it is a good idea @IreneGohtami . can you create a ticket on Jira for it.?

You can check this [post](https://magento.stackexchange.com/questions/108012/magento-2-get-the-current-currency-code), it shows how to get the currency code. @andykim

**Comment by andykim** [comment]
> > > I still prefer if we can show & hide, because our merchants would most likely on need either ID/PH & not both. This apply to the checkout page as well. @andykim
> > 
> > 
> > Ok. Let me try on this. Actually, Magento does not support it, so I need to customize our plugin.
> > But it is a good idea @IreneGohtami . can you create a ticket on Jira for it.?
> 
> You can check this [post](https://magento.stackexchange.com/questions/108012/magento-2-get-the-current-currency-code), it shows how to get the currency code. @andykim

yes, I see that. Actually it's not the main point. but it's ok. I'm doing a demo for it.

**Pull request merged**
